### ISSUE TITLE
Lacking F7G0112 MD5 Hash, Causes DOWNLOAD to Malfunction

### ISSUE THREAD

**Issue by MattyXarope** [ryanrudolfoba/SteamDeck-BIOS-Manager#15]
With commit 0b2ddd8 the DOWNLOAD function is not working correctly with OLED model - it simply erases all of the downloaded BIOS files because it is lacking the F7G0112 OLED md5.txt file hash. 

Adding this line fixes the problem:

`44f0243f662c6d279eb55cdb89089f7f  F7G0112_sign.fd`

Can anyone verify that the hash is correct for this file? It seems to be, as the downloaded files correctly remain in the BIOS folder, indicating that the hash is correct. I just wanted to double check.

**Comment by ryanrudolfoba** [comment]
[thanks for the heads up i've fixed it! added the md5 hash of BIOS F7G0112](https://github.com/ryanrudolfoba/SteamDeck-BIOS-Manager/commit/16d8bb9d751f1123341bfe5093b240389de2be95)

![image](https://github.com/user-attachments/assets/9364c7c4-2a51-4888-a6b3-7894157f2a44)
