### ISSUE TITLE
Desktop shortcut

### ISSUE THREAD

**Issue by Majkysek** [ryanrudolfoba/SteamDeck-BIOS-Manager#3]
Hi, I created a shortcut on my desktop to start the bios manager according to your comment on Youtube and it works fine. Can the script be modified so that I don't have to enter the password or so that it is entered automatically?

**Comment by ryanrudolfoba** [comment]
Since the script performs critical operations (BIOS flashing), having the correct sudo password is important. It is possible without password but i wouldnt recommend it.
