### ISSUE TITLE
How do I unlock 121 Bios?

### ISSUE THREAD

**Issue by himan250** [ryanrudolfoba/SteamDeck-BIOS-Manager#8]
What's New (as of February 10 2024)
Added BIOS F7A0121 for LCD model. This BIOS version allows for overclocking!

This appears to mean that the F7A0121 BIOS supports Overclock.
However, your program's SMOKELESS menu says it only allows BIOS 110 to 116.
How do I unlock 121 Bios?

**Comment by ryanrudolfoba** [comment]
sorry for the confusion - 121 BIOS doesnt allow overclock. 
only the latest OLED BIOS allows for overclock.

i'l update the repo soon to have OLED support. for LCD you still need to downgrade to 116 and then do smokeless.

i'll update the README about this.
