### ISSUE TITLE
Password sanity check fails on Bazzite

### ISSUE THREAD

**Issue by The-Synthax** [ryanrudolfoba/SteamDeck-BIOS-Manager#9]
Root user password check doesn't work on Bazzite.

Running the script on Bazzite fails with `Sudo password is blank! Setup a sudo password first and then re-run script!` providing a password here does seem to work, but upon running the script again it is still unable to detect that a sudo password has been set.

Removing the password sanity check section before running the script results in a normal superuser prompt, followed by the script working as expected.

**Comment by ryanrudolfoba** [comment]
This script is written for SteamOS. The sudo command in SteamOS behaves different on other distros thats why it fails the sanity check
